spring.application.name: kafka-cipher
server.port: 8081

spring:
  kafka:
    bootstrap-servers: "localhost:19092"
    producer:
      compression-type: "none"
      value-serializer: fr.axa.demo.kafka.SecuredObjectSerializer
      properties:
        "secret.key": ${secret.key}
    consumer:
      properties:
        "secret.key": ${secret.key}

logging.level:
  fr.axa.demo: DEBUG
  org.apache.kafka.clients.admin.AdminClientConfig: WARN
  org.apache.kafka.clients.producer.ProducerConfig: WARN
  org.apache.kafka.clients.producer.internals: WARN
  org.apache.kafka.clients.consumer.ConsumerConfig: WARN
  org.apache.kafka.clients.consumer.internals: WARN

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){faint} |%clr(%-5p){}|%clr(%-36.36logger{35}){cyan}| %m%n"
spring.output.ansi.enabled: ALWAYS

